/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ctr.stuba.xss.console.panel;

import ctr.stuba.xss.comm.mp.payload.SensorAddPayload;
import ctr.stuba.xss.console.comm.ManagementClientException;
import ctr.stuba.xss.console.impl.MainFrame;
import ctr.stuba.xss.sensor.Sensor;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.reflections.Reflections;

/**
 * Panel giving ability to create new sensor and add it to server.
 *
 * @author Lubomir Kaplan <castor@castor.sk>
 */
public class SensorListPanel extends DefaultPanel {

    private final MainFrame mainFrame;

    /**
     * Creates new form SensorListPanel
     */
    public SensorListPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    @Override
    public void initializeData() {
        Reflections reflections = new Reflections("ctr.stuba.xss.sensor.impl");
        Set<Class<? extends Sensor>> allClasses = reflections.getSubTypesOf(Sensor.class);
        List<String> stringList = new ArrayList<>();
        for (Class clazz : allClasses) {
            stringList.add(clazz.getName());
        }
        DefaultComboBoxModel sccbModel = new DefaultComboBoxModel(stringList.toArray(new String[stringList.size()]));
        this.guiNsClass.setModel(sccbModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        guiNsName = new javax.swing.JTextField();
        guiNsClass = new javax.swing.JComboBox();
        guiNsProbability = new javax.swing.JSpinner();
        guiNsEnabled = new javax.swing.JCheckBox();
        guiNsAutoToggleEnabled = new javax.swing.JCheckBox();
        guiNsAtStHr = new javax.swing.JSpinner();
        guiNsAtStMin = new javax.swing.JSpinner();
        guiNsAtStSec = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        guiNsAtEnHr = new javax.swing.JSpinner();
        guiNsAtEnMin = new javax.swing.JSpinner();
        guiNsAtEnSec = new javax.swing.JSpinner();
        guiNsAddButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiNsDesc = new javax.swing.JTextArea();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Sensor name:");

        jLabel3.setText("Sensor class:");

        jLabel4.setText("Random event probability:");

        jLabel5.setText("Administrative enabled:");

        jLabel6.setText("Auto-toggle enabled:");

        jLabel7.setText("Auto-toggle:");

        guiNsName.setText("SENSOR");

        guiNsClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        guiNsProbability.setModel(new javax.swing.SpinnerNumberModel(10, 10, 10000, 1));

        guiNsEnabled.setText("Enabled");

        guiNsAutoToggleEnabled.setText("Enabled");

        guiNsAtStHr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        guiNsAtStMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        guiNsAtStSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText("-");

        guiNsAtEnHr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        guiNsAtEnMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        guiNsAtEnSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        guiNsAddButton.setText("Add sensor");
        guiNsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNsAddButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("(0-10000)");

        jLabel9.setText("Description:");

        guiNsDesc.setColumns(20);
        guiNsDesc.setRows(5);
        jScrollPane1.setViewportView(guiNsDesc);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jScrollPane1)
                        .addContainerGap())
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
                                        .add(jLabel7)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsAtStHr))
                                    .add(jLabel6))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(guiNsAutoToggleEnabled)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .add(guiNsAtStMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsAtStSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsAtEnHr)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsAtEnMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsAtEnSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 201, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsClass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel4)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsProbability, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel8))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel5)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(guiNsEnabled)))
                                .add(0, 0, Short.MAX_VALUE)))
                        .add(182, 182, 182))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel9)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(guiNsAddButton)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(guiNsName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(guiNsClass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(guiNsProbability, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(guiNsEnabled))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(guiNsAutoToggleEnabled))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(guiNsAtStHr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(guiNsAtStMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(guiNsAtStSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(guiNsAtEnHr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(guiNsAtEnMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(guiNsAtEnSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(guiNsAddButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create sensor", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 659, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 560, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guiNsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNsAddButtonActionPerformed
        SensorAddPayload payload = new SensorAddPayload();
        payload.setAdminStatus(this.guiNsEnabled.isSelected());
        payload.setAutoToggleStatus(this.guiNsAutoToggleEnabled.isSelected());
        payload.setSensorName(this.guiNsName.getText());
        payload.setSensorClass((String) this.guiNsClass.getSelectedItem());
        payload.setDescription(this.guiNsDesc.getText());
        payload.setRegProbability((Integer) this.guiNsProbability.getValue());
        payload.setAutoToggleStart(((int) this.guiNsAtStHr.getValue() * 3600) + ((int) this.guiNsAtStMin.getValue() * 60) + ((int) this.guiNsAtStSec.getValue()));
        payload.setAutoToggleEnd(((int) this.guiNsAtEnHr.getValue() * 3600) + ((int) this.guiNsAtEnMin.getValue() * 60) + ((int) this.guiNsAtEnSec.getValue()));
        try {
            this.mainFrame.getManagementClient().addSensor(payload);
            this.mainFrame.redrawMenu();
        } catch (ManagementClientException ex) {
            Logger.getLogger(SensorListPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_guiNsAddButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiNsAddButton;
    private javax.swing.JSpinner guiNsAtEnHr;
    private javax.swing.JSpinner guiNsAtEnMin;
    private javax.swing.JSpinner guiNsAtEnSec;
    private javax.swing.JSpinner guiNsAtStHr;
    private javax.swing.JSpinner guiNsAtStMin;
    private javax.swing.JSpinner guiNsAtStSec;
    private javax.swing.JCheckBox guiNsAutoToggleEnabled;
    private javax.swing.JComboBox guiNsClass;
    private javax.swing.JTextArea guiNsDesc;
    private javax.swing.JCheckBox guiNsEnabled;
    private javax.swing.JTextField guiNsName;
    private javax.swing.JSpinner guiNsProbability;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
