package ctr.stuba.xss.hbm;
// Generated Mar 16, 2013 2:55:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * XssEvent generated by hbm2java
 */
public class XssEvent  implements java.io.Serializable {


     private Integer id;
     private String event;
     private String cause;
     private Integer sensorId;
     private String message;
     private Date time;

    public XssEvent() {
    }

	
    public XssEvent(String event, String cause, Date time) {
        this.event = event;
        this.cause = cause;
        this.time = time;
    }
    public XssEvent(String event, String cause, Integer sensorId, String message, Date time) {
       this.event = event;
       this.cause = cause;
       this.sensorId = sensorId;
       this.message = message;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public String getCause() {
        return this.cause;
    }
    
    public void setCause(String cause) {
        this.cause = cause;
    }
    public Integer getSensorId() {
        return this.sensorId;
    }
    
    public void setSensorId(Integer sensorId) {
        this.sensorId = sensorId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


