package ctr.stuba.xss.hbm;
// Generated Mar 16, 2013 2:55:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * XssUser generated by hbm2java
 */
public class XssUser  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private int enabled;
     private Date lastLoginTime;
     private Date createTime;

    public XssUser() {
    }

	
    public XssUser(String username, String password, int enabled, Date createTime) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
        this.createTime = createTime;
    }
    public XssUser(String username, String password, int enabled, Date lastLoginTime, Date createTime) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
       this.lastLoginTime = lastLoginTime;
       this.createTime = createTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


